Repository chainwayxyz/citrea, pull requests merged in 2024-08, with the labels that each got.

#943 RISC0 guest read optimization
  bin/citrea/src/lib.rs
  crates/risc0-bonsai/src/host.rs
  crates/sovereign-sdk/adapters/risc0/src/guest/native.rs
  crates/sovereign-sdk/adapters/risc0/src/guest/zkvm.rs
  crates/sovereign-sdk/adapters/risc0/src/host.rs
Labels: enhancement

#949 Fix Prove mode serialization panic
  crates/risc0-bonsai/src/host.rs
  crates/sovereign-sdk/adapters/mock-zkvm/src/lib.rs
  crates/sovereign-sdk/adapters/risc0/src/guest/mod.rs
  crates/sovereign-sdk/adapters/risc0/src/host.rs
  crates/sovereign-sdk/rollup-interface/src/state_machine/zk/mod.rs
Labels: bug

#959 RISC0 guest optimization: Compiler parameter optimizations & Lower memory copies
  Cargo.lock
  bin/citrea/provers/risc0/guest-bitcoin/Cargo.lock
  bin/citrea/provers/risc0/guest-bitcoin/Cargo.toml
  bin/citrea/provers/risc0/guest-mock/Cargo.toml
  crates/bitcoin-da/src/verifier.rs
  crates/risc0-bonsai/src/host.rs
  docs/run.md
Labels: enhancement

#968 Enable fast feature for ed25519-dalek
  Cargo.toml
Labels: enhancement

#933 Use Borsh ser/deser in TransactionWrapper and BitcoinHeaderWrapper
  crates/bitcoin-da/src/spec/header.rs
  crates/bitcoin-da/src/spec/transaction.rs
Labels: HOLD-MERGE

#983 Prover commitments grouping
  Cargo.lock
  bin/citrea/tests/e2e/reopen.rs
  crates/primitives/src/constants.rs
  crates/primitives/src/lib.rs
  crates/primitives/src/utils.rs
  crates/prover/src/runner.rs
  crates/sequencer/Cargo.toml
  crates/sequencer/src/sequencer.rs
  crates/sovereign-sdk/full-node/db/sov-db/src/ledger_db/mod.rs
  crates/sovereign-sdk/full-node/db/sov-db/src/ledger_db/rpc.rs
  crates/sovereign-sdk/full-node/db/sov-db/src/ledger_db/traits.rs
  crates/sovereign-sdk/full-node/db/sov-db/src/schema/tables.rs
  crates/sovereign-sdk/module-system/sov-modules-rollup-blueprint/src/lib.rs
  crates/sovereign-sdk/rollup-interface/src/state_machine/da.rs
Labels: HOLD-MERGE

#1031 Fix prover commitment serialization
  crates/bitcoin-da/src/service.rs
  crates/prover/src/prover_service/parallel/mod.rs
Labels: HOLD-MERGE
